### PR TITLE
HAGIWO Display Panel

### PR DESCRIPTION
**Pull request by modulove**
This Panel exposes the copper Layer to the front and is meant to be fabricated with ENIG plating.
We've made a hand full of this module, had some good fun and learned while making this.
Thought i push this back to the repository.

Cheers
Linus

### CODE REVIEW

**Comment by mzuelch** [comment]
Thanks for your contribution. Nice front!

**Comment by modulove** [comment]
If you're interested let me know and i will send you one.
Thanks for the nice module!

**Comment by mzuelch** [comment]
Since I'm a little bit on the engineering side of things, front panel design doesn't come this easy to me. I'm happy to use and also publish your designs!

**Comment by modulove** [comment]
I like your Designs a lot. Your published modules helping a lot to ease my #GAS and learn about making modules :)

Keep up the great work!

**Pull request merged**
